version: "3.9"

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped

  mcp:
    build: .
    env_file: .env
    depends_on:
      - redis
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: >
      sh -c "
        ngrok config add-authtoken $NGROK_AUTHTOKEN &&
        ngrok http 5300 --log=stdout &
        uv run -m app.server.mcp_server --host 0.0.0.0 --port 5300
      "
    ports:
      - "5300:5300"
    restart: unless-stopped

  slack_api:
    build: .
    env_file: .env
    depends_on:
      - redis
      - mcp
    # Runs FastAPI + ngrok (from Dockerfile CMD)
    command: sh -c "uvicorn app.services.slack_webhook:app --host 0.0.0.0 --port 8000 & ngrok http 8000 --log=stdout"
    ports:
      - "8000:8000" # Local access
    restart: unless-stopped

  vector_store:
    build: .
    env_file: .env
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: uv run -m app.tools.vector_store_tool --host 0.0.0.0 --port 5400
    ports:
      - "5400:5400"
    restart: unless-stopped
