version: "3.9"

services:
  vector_store:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["uv", "run", "-m", "app.tools.vector_store_tool"]
    restart: "no"

  mcp:
    build: .
    env_file:
      - .env
    depends_on:
      - vector_store
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - VECTOR_STORE_URL=${VECTOR_STORE_URL}
    command: ["uv", "run", "-m", "app.server.mcp_server"]
    ports:
      - "5300:5300"
    restart: unless-stopped

  slack_api:
    build: .
    env_file:
      - .env
    depends_on:
      - mcp
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MCP_SERVER_URL=${MCP_SERVER_URL}
    command: uv run uvicorn app.services.slack_webhook:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    command: http slack_api:8000 --domain=${NGROK_DOMAIN}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - slack_api
    ports:
      - "4040:4040"
    restart: unless-stopped
