version: "3.9"

services:
  slack_api:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["uv", "run", "uvicorn", "app.services.slack_webhook:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    restart: unless-stopped

  mcp:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["uv", "run", "python", "-m", "app.server.mcp_server"]
    ports:
      - "5300:5300"

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001" 
  ngrok:
    image: ngrok/ngrok:latest
    command: http slack_api:8000 --domain=${NGROK_DOMAIN}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - slack_api
    restart: unless-stopped