version: "3.9"

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped

  mcp:
    build: .
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./.venv:/app/.venv  # Shared virtual environment volume
    command: uvicorn app.server.mcp_server:app --host 0.0.0.0 --port 5300 --reload
    ports:
      - "5300:5300"
    restart: unless-stopped

  slack_api:
    build: .
    env_file: .env
    depends_on:
      - redis
      - mcp
    volumes:
      - ./.venv:/app/.venv  # Shared virtual environment volume
    command: uvicorn app.services.slack_webhook:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    restart: unless-stopped

  vector_store:
    build: .
    env_file: .env
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./.venv:/app/.venv  # Shared virtual environment volume
    command: uvicorn app.tools.vector_store_tool:app --host 0.0.0.0 --port 5400
    ports:
      - "5400:5400"
    restart: unless-stopped
