version: "3.9"

services:
  slack_api:
    build: .
    command: 
      uv run uvicorn app.services.slack_webhook:app
      --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  mcp:
    build: .
    command: uv run python -m app.server.mcp_server
    ports:
      - "5300:5300"
