version: "3.9"

services:
  slack_api:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uv run uvicorn app.services.slack_webhook:app
      --host 0.0.0.0 --port 8000
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped

  mcp:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uv run python -m app.server.mcp_server
    ports:
      - "5300:5300"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
